#!/bin/bash

set -e

# Atualizar cache de ícones do desktop
if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database -q /usr/share/applications
fi

# Atualizar cache de ícones
if [ -x /usr/bin/update-icon-caches ]; then
    /usr/bin/update-icon-caches /usr/share/icons/hicolor
fi

# Atualizar cache MIME
if [ -x /usr/bin/update-mime-database ]; then
    /usr/bin/update-mime-database /usr/share/mime
fi

echo "Xibo Player removido com sucesso!"

exit 0
