#!/bin/bash

set -e

# Update desktop icons cache
if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database -q /usr/share/applications
fi

# Update icons cache
if [ -x /usr/bin/update-icon-caches ]; then
    /usr/bin/update-icon-caches /usr/share/icons/hicolor
fi

# Update MIME cache
if [ -x /usr/bin/update-mime-database ]; then
    /usr/bin/update-mime-database /usr/share/mime
fi

echo "Xibo Player removed successfully!"

exit 0
